name: Create Kafka User

on:
  workflow_dispatch:
jobs:
  create-user:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t kafka-user-manager .

      - name: Run Kafka User Creation
        env:
          KAFKA_BROKER: ${{ secrets.KAFKA_BROKER }}
          KAFKA_ADMIN_USER: ${{ secrets.KAFKA_ADMIN_USER }}
          KAFKA_ADMIN_PASSWORD: ${{ secrets.KAFKA_ADMIN_PASSWORD }}
          KAFKA_USER: ${{ secrets.KAFKA_USER }}
          KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
        run: |
          docker run --rm \
            -e KAFKA_BROKER="${KAFKA_BROKER}" \
            -e KAFKA_ADMIN_USER="${KAFKA_ADMIN_USER}" \
            -e KAFKA_ADMIN_PASSWORD="${KAFKA_ADMIN_PASSWORD}" \
            -e KAFKA_USER="${KAFKA_USER}" \
            -e KAFKA_PASSWORD="${KAFKA_PASSWORD}" \
            -e ACTION="create" \
            kafka-user-manager
