name: Display Kafka User Credentials & ACLs

on:
  workflow_dispatch:  # Allows manual trigger
    inputs:
      kafka_user:
        description: 'Kafka Username'
        required: false
jobs:
  display-kafka-user:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t kafka-user-manager -f .github/workflows/Dockerfile .

      - name: Run Kafka User Display
        run: docker run --rm \
          -e KAFKA_BROKER="${{ secrets.KAFKA_BROKER }}" \
          -e KAFKA_ADMIN_USER="${{ secrets.KAFKA_ADMIN_USER }}" \
          -e KAFKA_ADMIN_PASSWORD="${{ secrets.KAFKA_ADMIN_PASSWORD }}" \
          -e KAFKA_USER="${{ inputs.kafka_user }}" \
          -e ACTION="display" \
          kafka-user-manager
