name: Kafka User Management

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main  # Runs when pushing to main branch

jobs:
  create-kafka-user:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Kafka CLI
        run: |
          wget https://downloads.apache.org/kafka/3.6.0/kafka_2.13-3.6.0.tgz
          tar -xzf kafka_2.13-3.6.0.tgz
          mv kafka_2.13-3.6.0 kafka
          echo "$(pwd)/kafka/bin" >> $GITHUB_PATH

      - name: Create Kafka User
        env:
          KAFKA_BROKER: ${{ secrets.KAFKA_BROKER }}
          KAFKA_USER: ${{ secrets.KAFKA_USER }}
          KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
        run: |
          kafka/bin/kafka-configs.sh --bootstrap-server $KAFKA_BROKER \
            --alter --add-config "SCRAM-SHA-512=[iterations=4096,password=$KAFKA_PASSWORD]" \
            --entity-type users --entity-name $KAFKA_USER

      - name: Verify Kafka User
        run: |
          kafka/bin/kafka-configs.sh --bootstrap-server $KAFKA_BROKER --describe --entity-type users
