name: Kafka User Management

on:
  workflow_dispatch:

jobs:
  create-kafka-user:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Kafka CLI
        run: |
          wget https://archive.apache.org/dist/kafka/3.6.0/kafka_2.12-3.6.0.tgz
          tar -xzf kafka_2.12-3.6.0.tgz
          mv kafka_2.12-3.6.0 kafka
          echo "$(pwd)/kafka/bin" >> $GITHUB_PATH

      - name: Create Kafka Config File
        run: |
          echo "security.protocol=SASL_PLAINTEXT" >> kafka_admin.properties
          echo "sasl.mechanism=SCRAM-SHA-256" >> kafka_admin.properties
          echo "sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username=\"${{ secrets.KAFKA_ADMIN_USER }}\" password=\"${{ secrets.KAFKA_ADMIN_PASSWORD }}\";" >> kafka_admin.properties

      - name: Create Kafka User
        env:
          KAFKA_BROKER: ${{ secrets.KAFKA_BROKER }}
          KAFKA_USER: ${{ secrets.KAFKA_USER }}
          KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
        run: |
          kafka/bin/kafka-configs.sh --bootstrap-server $KAFKA_BROKER \
            --alter --add-config "SCRAM-SHA-512=[iterations=4096,password=$KAFKA_PASSWORD]" \
            --entity-type users --entity-name $KAFKA_USER \
            --command-config kafka_admin.properties

      - name: Verify Kafka User
        run: |
          kafka/bin/kafka-configs.sh --bootstrap-server $KAFKA_BROKER \
            --describe --entity-type users --command-config kafka_admin.properties
