name: Update Kafka User Access

on:
  workflow_dispatch:
    inputs:
      kafka_user:
        description: 'Kafka Username'
        required: true
      kafka_topic:
        description: 'Kafka Topic'
        required: true
      access_level:
        description: 'Select Access Level (comma-separated: READ,WRITE,ALL)'
        required: true  
jobs:
  update-user-access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t kafka-user-manager -f .github/workflows/Dockerfile .

      - name: Run Kafka User Access Modification
        env:
          KAFKA_BROKER: ${{ secrets.KAFKA_BROKER }}
          KAFKA_ADMIN_USER: ${{ secrets.KAFKA_ADMIN_USER }}
          KAFKA_ADMIN_PASSWORD: ${{ secrets.KAFKA_ADMIN_PASSWORD }}
          KAFKA_USER: ${{ inputs.kafka_user }}
          KAFKA_TOPIC: ${{ inputs.kafka_topic }}
          ACCESS_LEVELS:  ${{ inputs.access_level }}      
        run: |
          docker run --rm \
            -e KAFKA_BROKER="${KAFKA_BROKER}" \
            -e KAFKA_ADMIN_USER="${KAFKA_ADMIN_USER}" \
            -e KAFKA_ADMIN_PASSWORD="${KAFKA_ADMIN_PASSWORD}" \
            -e KAFKA_USER="${KAFKA_USER}" \
            -e KAFKA_TOPIC="${KAFKA_TOPIC}" \
            -e ACCESS_LEVELS="${ACCESS_LEVELS}" \
            -e ACTION="update_user_access" \
            kafka-user-manager
